// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiidpjbdyohpbcbxyxpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpaWRwamJkeW9ocGJjYnh5eHBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NjE2MzQsImV4cCI6MjA2NTIzNzYzNH0.xGrGOj26EZ2IBhzPsKF0OoXDrVSsqs4p5_dN47YbcFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);